---
title: "scratch_paper"
output: html_document
date: "2023-10-17"
---

```{r}
library(dplyr)


setwd("C:/Users/Raymond/Documents/Classes/SDS625/Gymnastics-Data-Challenge/gymnastics copy")
men_best <- readRDS("best.teams.mens.rds")
women_best <- readRDS("best.teams.womens.rds")
means_df <- readRDS("means_df.rds")
key <- readRDS("name_ID_key.rds")
source("query.existing.database.R")
```

```{r}
means_df
```

```{r}
output <- list()
for(i in 1:12){
  for(app in apps){
    list(i, j) <- input$T{i}_{event}
  }
}
input$T{i}_{event}

```


```{r}
source("simulate_medals.R")
source("run_sims.R")

top12teams <- read.csv("data/team_country_qualified_individuals.csv")
qual36 <- read.csv("data/mens_36_athletes.csv")
means_df <- read.csv("data/means_per_app.csv")
stddevs_df <- read.csv("data/stddevs_per_app.csv")



output <- simulate_medals(top12teams, qual36, means_df, stddevs_df, "m")
```

```{r}
output
```



```{r}
men_best <- (readRDS("data/best.teams.mens.rds")$optimizedteams)# only men are optimizd
men_best <- men_best[men_best$Gender == "m", ]
women_best <- readRDS("data/best.teams.womens.rds")$optimizedteams # only women are optimized
women_best <- women_best[women_best$Gender == "w", ]

optimized_teams <- rbind(men_best, women_best)
saveRDS(optimized_teams, "optimized_teams.rds")
```

```{r}
source("get_default_assignments.R")
input <- top12teams[top12teams$Country == "USA" & top12teams$Gender == "w",]
get_default_assignments(top12teams[top12teams$Gender == "w",], means_df)
```

