---
title: "sim_medals"
output: html_document
date: "2023-09-24"
---

```{r}
# load mean and sd data
players_means <- read.csv("data/means_per_app.csv")
players_sds <- read.csv("data/stddevs_per_app.csv")


qual_teams <- read.csv("data/finaled_teams.csv")
# qual_teams <- data.frame(gender = c("m", "w"), 
#                          T1 = "CHN", T2 = "JPN", T3 = "GBR", T4 = "ESP", T5="USA",
#                          T6 = "FRA", T7="AUS", T8="ITA")
qual_aa <- read.csv("data/finaled_aas.csv")
qual_ind <- read.csv("data/finaled_events.csv")

# the output df, tallying the number of each medal for each country
country_medals <- data.frame(
  Country = unique(players_means$Country),
  Golds = 0, Silvers = 0, Bronzes = 0
)

# use as dictionary to get the country of each ID (player)
ID_country_dict <- players_means[, c("ID", "Country")]
ID_country_dict <- ID_country_dict[!duplicated(ID_country_dict$ID, fromLast=T), ]

# define the male and female events
m_apps <- c("VT", "FX", "HB", "PB", "PH", "SR")
f_apps <- c("VT", "BB", "UB", "FX")
```


# Simulate Team Finals (M)
```{r}
country_scores_m <- data.frame(
  country = as.character(qual_teams[1, 2:9]),
  scores = rep(0, 8), 
  nas = rep(0, 8)
)
for(i in 2:9){
  country <- qual_teams[1, i]
  n_nas <- 0
  for(app in m_apps){
    curr_df <- players_means[players_means$gender == "m" & players_means$Country == country,]
    top3 <- order(-curr_df[, app])[1:3]
    top3_id <- curr_df$ID[top3]
    for(id in top3_id){
      score <- rnorm(1, 
                     mean=players_means[players_means$ID==id, app],
                     sd=players_sds[players_sds$ID==id, app]
                  )
      if(!is.na(score)){ # only add if not na, and tally up nas
        country_scores_m$scores[country_scores_m$country == country] <- country_scores_m$scores[country_scores_m$country == country] + score
      }
      else{
        n_nas <- n_nas + 1
      }
    }
  }
  country_scores_m$nas[country_scores_m$country == country] <- n_nas
}

#assigning medals
top3_countries <- country_scores_m$country[order(-country_scores_m$scores)[1:3]]
country_medals$Golds[country_medals$Country == top3_countries[1]] = country_medals$Golds[country_medals$Country == top3_countries[1]] + 1
country_medals$Silvers[country_medals$Country == top3_countries[2]] = country_medals$Silvers[country_medals$Country == top3_countries[2]] + 1
country_medals$Bronzes[country_medals$Country == top3_countries[3]] = country_medals$Bronzes[country_medals$Country == top3_countries[3]] + 1
```


# Simulate Teams Finals (W)
```{r}
country_scores_f <- data.frame(
  country = as.character(qual_teams[2, 2:9]),
  scores = rep(0, 8), 
  nas = rep(0, 8)
)

for(i in 2:9){
  country <- qual_teams[2, i]
  n_nas <- 0
  for(app in f_apps){
    curr_df <- players_means[players_means$gender == "w" & players_means$Country == country,]
    top3 <- order(-curr_df[, app])[1:3]
    top3_id <- curr_df$ID[top3]
    for(id in top3_id){
      score <- rnorm(1, 
                     mean=players_means[players_means$ID==id, app],
                     sd=players_sds[players_sds$ID==id, app]
                  )
      if(!is.na(score)){
        country_scores_f$scores[country_scores_f$country == country] <- country_scores_f$scores[country_scores_f$country == country] + score
      }
      else{
        n_nas <- n_nas + 1
      }
      # print(c(country, app, id, score))
    }
  }
  country_scores_f$nas[country_scores_f$country == country] <- n_nas
}

#assigning medals
top3_countries <- country_scores_f$country[order(-country_scores_f$scores)[1:3]]
country_medals$Golds[country_medals$Country == top3_countries[1]] = country_medals$Golds[country_medals$Country == top3_countries[1]] + 1
country_medals$Silvers[country_medals$Country == top3_countries[2]] = country_medals$Silvers[country_medals$Country == top3_countries[2]] + 1
country_medals$Bronzes[country_medals$Country == top3_countries[3]] = country_medals$Bronzes[country_medals$Country == top3_countries[3]] + 1
```


# Simulate AA Finals(M)
```{r}
aa_scores_m <- data.frame(
  ID = as.character(qual_aa[1, 2:25]),
  scores = rep(0, 24),
  nas = rep(0, 24)
)

for(i in 2:25){
  n_nas <- 0
  id <- qual_aa[1, i]
  for(app in m_apps){
      score <- rnorm(1,
                     mean=players_means[players_means$ID==id, app],
                     sd=players_sds[players_sds$ID==id, app]
                  )
      if(!is.na(score)){
        aa_scores_m$scores[aa_scores_m$ID == id] <- aa_scores_m$scores[aa_scores_m$ID == id] + score
      }
      else{
        n_nas <- n_nas + 1
      }
  }
  aa_scores_m$nas[aa_scores_m$ID == id] <- n_nas
}

#assigning medals
top3_i <- aa_scores_m$ID[order(-aa_scores_m$scores)[1:3]]
top3_countries <- as.character(sapply(top3_i, function(i) ID_country_dict$Country[ID_country_dict$ID == i]))
country_medals$Golds[country_medals$Country == top3_countries[1]] = country_medals$Golds[country_medals$Country == top3_countries[1]] + 1
country_medals$Silvers[country_medals$Country == top3_countries[2]] = country_medals$Silvers[country_medals$Country == top3_countries[2]] + 1
country_medals$Bronzes[country_medals$Country == top3_countries[3]] = country_medals$Bronzes[country_medals$Country == top3_countries[3]] + 1
```


# Simulate AA Finals(F)
```{r}
aa_scores_f <- data.frame(
  ID = as.character(qual_aa[2, 2:25]),
  scores = rep(0, 24),
  nas = rep(0, 24)
)

for(i in 2:25){
  n_nas <- 0
  id <- qual_aa[2, i]
  for(app in f_apps){
      score <- rnorm(1,
                     mean=players_means[players_means$ID==id, app],
                     sd=players_sds[players_sds$ID==id, app]
                  )
      if(!is.na(score)){
        aa_scores_f$scores[aa_scores_f$ID == id] <- aa_scores_f$scores[aa_scores_f$ID == id] + score
      }
      else{
        n_nas <- n_nas + 1
      }
  }
  aa_scores_f$nas[aa_scores_f$ID == id] <- n_nas
}
top3_i <- aa_scores_f$ID[order(-aa_scores_f$scores)[1:3]]
top3_countries <- as.character(sapply(top3_i, function(i) ID_country_dict$Country[ID_country_dict$ID == i]))
country_medals$Golds[country_medals$Country == top3_countries[1]] = country_medals$Golds[country_medals$Country == top3_countries[1]] + 1
country_medals$Silvers[country_medals$Country == top3_countries[2]] = country_medals$Silvers[country_medals$Country == top3_countries[2]] + 1
country_medals$Bronzes[country_medals$Country == top3_countries[3]] = country_medals$Bronzes[country_medals$Country == top3_countries[3]] + 1
```


# Simulate Event Finals
```{r}
get_event_final_scores <- function(gender, app, IDs){
  out_df <- data.frame(
    ID = IDs,
    gender = rep(gender, length(IDs)),
    app = rep(app, length(IDs)),
    score = rep(0, length(IDs))
  )
  out_df$Score <- sapply(out_df$ID, 
                         function(id) rnorm(1,
                                            mean=players_means[players_means$ID==id, app],
                                            sd=players_sds[players_sds$ID==id, app]
                                            )
                         )
  return(out_df)
}
```


```{r}
for(i in 1:dim(qual_ind)[1]){
  curr_event <- qual_ind[i, ] 
  scores <- get_event_final_scores(curr_event$Gender, curr_event$App, as.character(curr_event[, 3:ncol(curr_event)]))
  
  top3_i <- scores$ID[order(-scores$score)[1:3]]
  top3_countries <- as.character(sapply(top3_i, function(i) ID_country_dict$Country[ID_country_dict$ID == i]))
  country_medals$Golds[country_medals$Country == top3_countries[1]] = country_medals$Golds[country_medals$Country == top3_countries[1]] + 1
  country_medals$Silvers[country_medals$Country == top3_countries[2]] = country_medals$Silvers[country_medals$Country == top3_countries[2]] + 1
  country_medals$Bronzes[country_medals$Country == top3_countries[3]] = country_medals$Bronzes[country_medals$Country == top3_countries[3]] + 1
  
}
```

```{r}
write.csv(country_medals, "data/medalling_outputs.csv", row.names=F)
```

```{r}
country_medals
```



To-Do: load qual_team and qual_ind in properly, and output the medals df






